<?php

namespace Astra\SharedBundle\Repository;

/**
 * AccessGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
