<?php

namespace Astra\SharedBundle\Repository;

use Astra\SharedBundle\Entity\Directory;
use Astra\SharedBundle\Entity\User;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFileForDirectoryAndUser(User $user, Directory $directory = null)
    {
        $params = [];

        $queryBuilder = $this->createQueryBuilder('file')
            ->where('file.user = :user')->setParameter('user',$user);

        if(($directory)&&($directory->getId()))
        {
            $queryBuilder->andWhere('file.directory = :directory')->setParameter('directory',$directory);
        }
        else
        {
            $queryBuilder->andWhere('file.directory IS NULL');
        }

        return $queryBuilder->getQuery()->getResult();

    }
}
