<?php

namespace Astra\SharedBundle\Repository;

/**
 * ProjectUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
