<?php

namespace Astra\SharedBundle\Repository;

/**
 * ProjectDirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectDirectoryRepository extends \Doctrine\ORM\EntityRepository
{
}
