<?php

namespace Astra\SharedBundle\Repository;

use Astra\SharedBundle\Entity\Directory;
use Astra\SharedBundle\Entity\File;
use Astra\SharedBundle\Entity\Project;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * ProjectFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskFileRepository extends EntityRepository
{

}
