<?php

namespace Astra\SharedBundle\Repository;

/**
 * WalletTransactionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WalletTransactionItemRepository extends \Doctrine\ORM\EntityRepository
{
}
